Saving example seq files in TestStand 2021 SP1 with final build of Me…
ni/measurementlink-python pull request #226
Opened 2023-02-09 22:52 UTC by DelpireNI

…asurementLink.

Signed-off-by: Chris Delpire <chris.delpire@ni.com>

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-python/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Opened all example seq files in TestStand 2021 SP1, upgraded the types to the latest, and saved the file.

### Why should this Pull Request be merged?

Customers opening the seq file in TestStand 2021 will see a dialog warning about a step type mismatch if we do not update them.

Unfortunately, they will still have this dialog with TestStand 2022.

### What testing has been done?

Opened seq file in TestStand 2021 SP1 and did not see the dialog. It would be nice if someone could test this with TestStand 2021 (non-SP1 build).

2023-02-10 14:35 UTC, pbirkhol-ni requested changes
I think you should resave these again once Jonathan's change has been submitted and cherry picked.

2023-02-10 15:32 UTC, DelpireNI commented
> I think you should resave these again once Jonathan's change has been submitted and cherry picked.

Yes that sounds good. I just wanted this up incase we decided not to cherry pick.

2023-02-13 22:26 UTC, DelpireNI commented
@pbirkhol-ni Updated with seq files saved in TS2021 SP1 and MeasurementLink 23.0 f902.

2023-02-13 22:31 UTC, bkeryan approved these changes

2023-02-13 22:33 UTC, pbirkhol-ni approved these changes

2023-02-13 22:34 UTC, merged