README.md: Move example content into examples/README.md
ni/measurementlink-python pull request #227
Opened 2023-02-13 23:06 UTC by bkeryan

Signed-off-by: Brad Keryan <brad.keryan@ni.com>

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-python/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Move the example content from /README.md to /examples/README.md

### Why should this Pull Request be merged?

Hyperlink the PyPI README to the examples directory on GitHub.
Shorten the README that we upload to PyPI.

### What testing has been done?

None

2023-02-13 23:15 UTC, DelpireNI approved these changes

2023-02-14 13:53 UTC, dixonjoel requested changes

2023-02-14 13:53 UTC, dixonjoel commented on README.md
>  To Statically register the examples provided, the user can copy the example directory with the service config file with the startup batch file, to the search paths and follow the [Setting up the Exam
This paragraph is worded awkwardly. I'd suggest
- Statically should not be capitalized.
- 'with the .serviceconfig file *and* the startup batch file
- No comma after 'the startup batch file'
- What does 'to the search paths' mean? Is that explained elsewhere?
- Doesn't this Setting up the Example Measurements link need to go to an external file now? We removed the section above.

2023-02-14 13:54 UTC, dixonjoel commented
@bkeryan do you want this to go in before we make a release today or does it matter?

2023-02-14 14:31 UTC, pbirkhol-ni approved these changes

2023-02-14 14:31 UTC, pbirkhol-ni commented on examples/README.md
> +The example measurements shared are *poetry-based* projects. Follow the below steps to  for setting up the example measurement:
```suggestion
The example measurements are *poetry-based* projects. Follow the steps below for setting up the example measurement:
```

2023-02-14 14:31 UTC, pbirkhol-ni commented on examples/README.md
> +3. Run `poetry install`. This command creates/updates the .venv and installs all the dependencies(including `ni-measurementlink-service` package) needed for the Example into `.venv`
```suggestion
3. Run `poetry install`. This command creates/updates the .venv and installs all the dependencies(including `ni-measurementlink-service` package) needed for the example into `.venv`
```

2023-02-14 15:08 UTC, bkeryan commented
> @bkeryan do you want this to go in before we make a release today or does it matter?

Yes, I'd like to verify that the PyPI readme doesn't have any broken links.

2023-02-14 15:15 UTC, dixonjoel approved these changes

2023-02-14 15:56 UTC, merged