Updated the TestStand sequence of NI DCPower measurement to make it simpler
ni/measurementlink-python pull request #249
Opened 2023-04-25 07:49 UTC by Tharun-Sundar

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-python/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?
- Updates the TestStand sequence in the DC-Power example measurement to make it simpler by moving the process setup and process cleanup steps to the main sequence.
- Combines the logic for registering pin map into a single step in the Setup section. Previously this was handled in three steps.

### Why should this Pull Request be merged?
Based on the feedback discussed in this [Teams post](https://teams.microsoft.com/l/message/19:36f0e963feb84c0c8122e6ddfbe7df7b@thread.tacv2/1676494204834?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=a092c504-be1c-4d21-9ef4-068a40ca6974&parentMessageId=1676494204834&teamName=MeasurementLink%20%26%20ETW%20Global%20Collaboration&channelName=Roadmap%20Input%20and%20Feature%20Ideas&createdTime=1676494204834&allowXTenantAccess=false), moving the process setup and process cleanup steps to the main sequence will simplify the example sequence as the user will only need to run the main sequence to get the expected result. Though this sequence is not efficient for multi-site use case, this change is encouraged as the example sequence is expected to be tailored to users who are beginners in TestStand.

### What testing has been done?
Manually executed the TestStand example sequence with a simulated DC-Power instrument and verified the result.

2023-04-25 14:33 UTC, dixonjoel approved these changes

2023-04-26 17:22 UTC, Tharun-Sundar commented
@bkeryan When executing the TestStand sequence, the pin map file is not found even if it is available in the sequence directory. I updated the code as shown below to make sure that the logic is similar to the LabVIEW example sequence.
```
sequence_file = self._sequence_context.SequenceFile
(_, file_path, _, _, _) = self._sequence_context.Engine.FindFileEx(file_name, searchContext=sequence_file)
return file_path
```
But it is not having any impact in the search. Please share your thoughts on this.

2023-04-27 13:55 UTC, bkeryan requested changes

2023-04-27 13:55 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltage.seq
Please configure the Python adapter consistently for the setup/cleanup steps. The other sequences uncheck **Use Adapter Settings for Python Interpreter** in order to use the example program's virtualenv. They also explicitly specify Python 3.9.

![image](https://user-images.githubusercontent.com/17914399/234883889-c755dd69-784f-4a30-b747-5ee71cc68e54.png)

2023-04-27 15:41 UTC, vigkre commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +        Args:
Added Returns block

2023-04-27 15:55 UTC, vigkre commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +        (_, file_path, _, _, _) = self._sequence_context.Engine.FindFileEx(file_name)
Added `searchContext` to specify sequence file path.

2023-04-27 15:56 UTC, vigkre commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +    def __init__(self, sequence_context) -> None:
Annotated the type as `Any` for `sequence_context` COM Object

2023-04-27 15:56 UTC, vigkre commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +    def update_pin_map(self, pin_map_id: str) -> str:
Updated

2023-04-27 15:56 UTC, vigkre commented on examples/nidcpower_source_dc_voltage/_helpers.py
Added Returns block

2023-04-27 15:58 UTC, vigkre commented on examples/nidcpower_source_dc_voltage/teststand_fixture.py
> +    pin_map_full_path = teststand_support.get_file_path(pin_map_path)
Renamed to `pin_map_abs_path`

2023-04-27 15:59 UTC, vigkre commented on examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltage.seq
Configured Python adapter settings for setup/cleanup steps. Updated Python version to 3.9

2023-04-28 05:55 UTC, bkeryan commented
> @bkeryan When executing the TestStand sequence, the pin map file is not found even if it is available in the sequence directory. I updated the code as shown below to make sure that the logic is similar to the LabVIEW example sequence.
> 
> ```
> sequence_file = self._sequence_context.SequenceFile
> (_, file_path, _, _, _) = self._sequence_context.Engine.FindFileEx(file_name, searchContext=sequence_file)
> return file_path
> ```
> 
> But it is not having any impact in the search. Please share your thoughts on this.

When you call `FindFileEx`, the `win32com` module dynamically generates this code:
> `"def FindFileEx(self, fileToFind=pythoncom.Missing, absolutePath=pythoncom.Missing, srchDirType=pythoncom.Missing, searchDirectoryIndex=pythoncom.Missing\n\t\t\t, userCancelled=pythoncom.Missing, promptOption=1, srchListOption=1, isCommand=False, searchContext=pythoncom.Missing\n\t\t\t, reserved=pythoncom.Missing):\n\treturn self._ApplyTypes_(1050, 1, (11, 0), ((8, 1), (16392, 2), (16387, 2), (16387, 2), (16395, 2), (3, 49), (3, 49), (11, 49), (12, 17), (12, 17)), 'FindFileEx', None,fileToFind\n\t\t\t, absolutePath, srchDirType, searchDirectoryIndex, userCancelled, promptOption\n\t\t\t, srchListOption, isCommand, searchContext, reserved)\n"`

When you call `FindFileEx(file_name, searchContext=sequence_file)`, this leaves `absolutePath`, `srchDirType`, etc. unspecified, so they default to `pythoncom.Missing`.

The problem is that `PyIDispatch`  stops passing parameters when it encounters `pythoncom.Missing`: https://github.com/mhammond/pywin32/blob/main/com/win32com/src/PyIDispatch.cpp#L369

Passing `None` for the output parameters seems to work. I initially tried it with positional arguments:
```
        (_, file_path, _, _, _) = self._sequence_context.Engine.FindFileEx(
            file_name, # fileToFind
            None, # absolutePath
            None, # srchDirType
            None, # searchDirectoryIndex
            None, # userCancelled
            1, # promptOption=FindFile_PromptHonorUserPreference
            1, # srchListOption=FindFile_SrchAskUser
            False, # isCommand
            self._sequence_context.SequenceFile, # searchContext
        )
        return file_path
```

Using keyword arguments allows us to leave `promptOption`, `srchListOption`, and `isCommand` unspecified. Their default values are defined in TestStand's IDL, so leaving them unspecified does the right thing.

Let's do this:
```
        (_, file_path, _, _, _) = self._sequence_context.Engine.FindFileEx(
            fileToFind=file_name,
            absolutePath=None,
            srchDirType=None,
            searchDirectoryIndex=None,
            userCancelled=None,
            searchContext=self._sequence_context.SequenceFile,
        )
        return file_path
```

2023-04-28 15:23 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +    def __init__(self, sequence_context) -> None:
I was referring to the COM object parameter, not the return value.

I will push a couple of commit to update the type annotations and docstrings.

2023-04-28 15:29 UTC, bkeryan requested changes

2023-04-28 15:29 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +    def get_pin_map_id_temporary_variable(self) -> str:
Get and set should be symmetric.

2023-04-28 15:29 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +    def get_file_path(self, file_path: str) -> str:
This should be named resolve like in LV.

2023-04-28 15:55 UTC, bkeryan requested changes

2023-04-28 15:55 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +            file_path, searchContext=sequence_file
This seems to return "." when you pass in an absolute file path or you click cancel on the file dialog, which is not what we want.

2023-04-28 16:00 UTC, bkeryan requested changes

2023-04-28 16:05 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +        (_, abs_file_path, _, _, _) = self._sequence_context.Engine.FindFileEx(
I suppose this isn't a new issue, though. And I don't see any way to make FindFileEx behave differently. Marking resolved.

2023-04-28 16:06 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltage.seq
Update Pin Map still has "Use Adapter Settings for Python Interpreter" checked.

![image](https://user-images.githubusercontent.com/17914399/235198285-1cdac80b-3d81-4902-8364-c19d3ca3be09.png)

2023-04-28 16:08 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +    def get_pin_map_id_temporary_variable(self) -> str:
Fixed

2023-04-28 16:08 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +            file_path, searchContext=sequence_file
Fixed:
- Check for absolute paths before calling FindFileEx
- Check userCancelled output

2023-04-28 16:08 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +    def __init__(self, sequence_context) -> None:
Fixed

2023-04-28 16:09 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltage.seq
Fixed

2023-04-28 16:12 UTC, bkeryan requested changes

2023-04-28 16:12 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +        pin_map_purepath = pathlib.Path(pin_map_path)
This is not a pathlib.PurePath. pathlib.PurePath is like pathlib.Path except it doesn't support filesystem access, and this function performs filesystem access.

2023-04-28 16:19 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +        pin_map_purepath = pathlib.Path(pin_map_path)
Fixed

2023-04-28 16:20 UTC, bkeryan approved these changes

2023-04-28 16:44 UTC, merged

2023-04-28 16:45 UTC, bkeryan commented on examples/nidcpower_source_dc_voltage/_helpers.py
> +        pin_map_purepath = pathlib.Path(pin_map_path)
Renamed