Removing reservation timeout and instrument ID from reserve_session c…
ni/measurementlink-python pull request #393
Opened 2023-09-21 16:06 UTC by DelpireNI

…alls in our examples.

- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-python/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Removing the reservation timeout and instrument id parameters from our reserve_session calls in our examples.

### Why should this Pull Request be merged?

Removing these parameters shorten and simply our examples. 

`instrument_type_id` can be removed for the following reasons:
- InstrumentStudio pin controls already filter by instrument type.
- In TestStand you will get an error if you specify a pin that is connected to the wrong instrument type.
- Connecting one pin to multiple instruments is an advanced use case.

Note that we are leaving this in the TestStand code modules. 

`timeout` has added 7 lines of boilerplate to our example. A reservation of 0 seconds (the default) should be sufficient for single-site, single-threaded test sequences.

### What testing has been done?

Tested the DMM example against a simulated device in NI-MAX.

2023-09-21 16:15 UTC, dixonjoel commented
Please add AB#2524066 in the PR description if that is accurate.

2023-09-21 16:17 UTC, dixonjoel approved these changes

2023-09-21 16:17 UTC, dixonjoel commented
I think you should wait for @bkeryan to review before submitting.

2023-09-21 19:50 UTC, bkeryan requested changes

2023-09-21 19:50 UTC, bkeryan commented on examples/nidaqmx_analog_input/measurement.py
> Tested the DMM example against a simulated device in NI-MAX.

Please test all of the examples. Except for `nidaqmx_analog_input`, they all use session-based simulation by default.

Also, make sure to test the examples in TestStand, not only InstrumentStudio.

2023-09-21 19:50 UTC, bkeryan commented on examples/nidaqmx_analog_input/teststand_fixture.py
You missed some reservation timeouts. (Some of these are not reservation timeouts, but most of them are.)
```
PS D:\dev\measurementlink-python> rg timeout= .\examples\
.\examples\output_voltage_measurement\teststand_nidcpower.py
52:            timeout=0,

.\examples\output_voltage_measurement\teststand_nivisa_dmm.py
61:            timeout=0,

.\examples\output_voltage_measurement\measurement.py
191:            channels.wait_for_event(nidcpower.enums.Event.SOURCE_COMPLETE, timeout=0.1)

.\examples\nivisa_dmm_measurement\teststand_fixture.py
83:            timeout=0,

.\examples\niswitch_control_relays\teststand_fixture.py
80:            timeout=0,

.\examples\niscope_acquire_waveform\teststand_fixture.py
80:            timeout=0,

.\examples\nifgen_standard_function\teststand_fixture.py
79:            timeout=0,

.\examples\nidmm_measurement\teststand_fixture.py
79:            timeout=0,

.\examples\nidigital_spi\teststand_fixture.py
168:            timeout=0,

.\examples\nidcpower_source_dc_voltage\teststand_fixture.py
79:            timeout=0,

.\examples\nidcpower_source_dc_voltage\measurement.py
111:                        channels.wait_for_event(nidcpower.enums.Event.SOURCE_COMPLETE, timeout=0.1)

.\examples\nidaqmx_analog_input\teststand_fixture.py
80:            timeout=0,

.\examples\nidaqmx_analog_input\measurement.py
78:                number_of_samples_per_channel=number_of_samples, timeout=timeout
```

2023-09-22 15:51 UTC, bkeryan approved these changes

2023-09-22 17:13 UTC, DelpireNI commented on examples/nidaqmx_analog_input/measurement.py
I was able to successfully run all our examples that use hardware in both TestStand and InstrumentStudio. PR description updated.

2023-09-22 17:21 UTC, merged