[PR1] Split the TestStand modules into specific modules for the nidcpower, nidigital and nidaqmx examples
ni/measurementlink-python pull request #460
Opened 2023-10-17 09:29 UTC by samchris007

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-python/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?
Split TestStand code modules in the examples by pinmap-specific and driver-specific logic and updated the TestStand sequences accordingly.

The `nidcpower_source_dc_voltage`, `nidaqmx_analog_input`, and `nidigital_spi` examples' TestStand code modules are split into driver-specific and pin map-specific code.

**Note**: Since we have already split the TestStand code for the `teststand_nidcpower.py` in the `output_voltage_measurement`, we have reused the same code splitting for the `nidcpower_source_dc_voltage`.
### Why should this Pull Request be merged?

Implements https://github.com/ni/measurementlink-python/issues/392 for `nidcpower_source_dc_voltage`, `nidaqmx_analog_input`, and `nidigital_spi` examples

### What testing has been done?

- Manually tested by running the sequence examples 
- Ran the existing tests.

2023-10-18 10:02 UTC, keer1111 approved these changes
Approved with suggestions

2023-10-18 12:33 UTC, samchris007 commented on examples/nidaqmx_analog_input/NIDAQmxAnalogInput.seq
> -<teststandfileheader type='SequenceFile' fileversion='962' productname='TestStand' productversion='2021 SP1 (21.1.0.49154)' compatibleversion='21.0.0.0' buildversion='21.0.0.49156' xmlns:xsi="http://
Sure. Updated the sequences.

2023-10-18 14:35 UTC, dixonjoel approved these changes

2023-10-18 16:16 UTC, bkeryan requested changes

2023-10-18 16:18 UTC, samchris007 commented on examples/nidcpower_source_dc_voltage/_nidcpower_helpers.py
I'm not seeing these errors on my machine. Can you please check if this is the case for any of the other examples in your machine?

2023-10-18 16:24 UTC, dixonjoel commented on examples/nidcpower_source_dc_voltage/_nidcpower_helpers.py
I'm not seeing them on another test machine. I believe it a setup problem on my dev machine. So I'm going to resolve this.

2023-10-19 07:15 UTC, samchris007 commented on examples/nidaqmx_analog_input/teststand_pin_map.py
> +        pin_map_path:
Sure. Moved the description to the same line as the parameter name.

2023-10-19 18:29 UTC, bkeryan approved these changes

2023-10-19 20:29 UTC, merged