[PR2] Split the TestStand modules into specific modules for pinmap and driver specific logic
ni/measurementlink-python pull request #461
Opened 2023-10-17 14:43 UTC by samchris007

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-python/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?
Split TestStand code modules in the examples by pinmap-specific and driver-specific logic and updated the TestStand sequences accordingly.

The `nidmm_measurement`, `nifgen_standard_function`, and `niscope_acquire_waveform` examples' TestStand code modules are split into driver-specific and pin map-specific code.

### Why should this Pull Request be merged?

Implements https://github.com/ni/measurementlink-python/issues/392 for `nidmm_measurement`, `nifgen_standard_function`, and `niscope_acquire_waveform` examples

### What testing has been done?

- Manually tested by running the sequence examples 
- Ran the existing tests.

2023-10-18 12:36 UTC, keer1111 approved these changes

2023-10-18 12:37 UTC, keer1111 commented on examples/nidmm_measurement/NIDmmMeasurement.seq
> +<teststandfileheader type='SequenceFile' fileversion='962' productname='TestStand' productversion='2021 (21.0.0.49156)' compatibleversion='21.0.0.0' buildversion='21.0.0.49156' xmlns:xsi="http://www.
version check

2023-10-18 15:14 UTC, dixonjoel commented on examples/nidmm_measurement/NIDmmMeasurement.seq
I get this error when I try to run the sequence. Did you encounter this and how did you get around it?
> Error: Error executing substep 'Post'.
Exception iterating responses: The SESSION_MANAGEMENT_2024Q1 feature is not supported at the current code readiness level.  To enable it, set MEASUREMENTLINK_ENABLE_SESSION_MANAGEMENT_2024Q1 or MEASUREMENTLINK_ALLOW_INCOMPLETE.[Error Code: -17500, Operation Failed. ]

2023-10-18 15:28 UTC, dixonjoel commented on examples/nidmm_measurement/NIDmmMeasurement.seq
I was able to overcome this by making a .env file in the root directory of the repo and uncommenting the MEASUREMENTLINK_ENABLE_SESSION_MANAGEMENT_2024Q1 line. I did have to do 'poetry install' on the measurement service again.

2023-10-18 15:29 UTC, dixonjoel approved these changes

2023-10-18 16:18 UTC, bkeryan requested changes

2023-10-18 16:18 UTC, bkeryan commented on examples/nidmm_measurement/teststand_pin_map.py
> +        pin_map_path:
https://github.com/ni/measurementlink-python/pull/460#discussion_r1364150727

2023-10-19 07:13 UTC, samchris007 commented on examples/nidmm_measurement/NIDmmMeasurement.seq
Yes, that's correct. To run the example measurements with the new session APIs, you need to enable the feature toggle using the `.env` file.  This information has been mentioned [here](https://github.com/ni/measurementlink-python/blob/6d8540ca3bb2b19435252d3b63bde5cdfd86fe18/.env.sample#L4) in our repo

2023-10-19 18:30 UTC, bkeryan approved these changes

2023-10-19 20:29 UTC, merged